el proyecto no arranca `$npm run dev`
src/models/User.js:1
(function (exports, require, module, __filename, __dirname) { UserSchema.methods.encryptPassword = async (password) => {
                                                              ^

ReferenceError: UserSchema is not defined
    at Object.<anonymous> (src/models/User.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

node -v 10.14.1
npm -v 6.4.1